Database_1/Controllers/CartsController.cs
using Database_1.Models;
using Database_1.ViewModels;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Database_1.Controllers
{
	public class CartsController : Controller
	{
		private readonly ApplicationDbContext _context;
		public CartsController()
		{
			_context = new ApplicationDbContext();
		}
		// GET: Carts
		public ActionResult Index()
		{
			var carts = _context.Carts
				.Include(s => s.Customer)
				.Include(s => s.Product)
				.ToList();
			return View(carts);
		}

		[Authorize(Roles = "guest")]
		[HttpGet]
		public ActionResult Create()
		{
			var viewModel = new CartViewModel
			{
				Products = _context.Products.ToList()
			};


			return View(viewModel);
		}

		[Authorize(Roles = "guest")]
		[ValidateAntiForgeryToken]
		[HttpPost]
		public ActionResult Create(Product product)
		{
			Cart cart = new Cart
			{
				CustomerId = User.Identity.GetUserId(),
				ProductId = product.Id
			};

			_context.Carts.Add(cart);
			_context.SaveChanges();
			return RedirectToAction("Mine");
		}

		[HttpGet]
		[Authorize(Roles = "guest")]
		public ActionResult Mine()
		{
			var userId = User.Identity.GetUserId();

			var carts = _context.Carts
				.Where(c => c.CustomerId == userId)
				.Include(c => c.Product)
				.ToList();

			return View(carts);
		}

		//DELETE for admin and customer
		[HttpGet]
		public ActionResult Delete(int id)
		{
			var cartInDb = _context.Carts.SingleOrDefault(p => p.Id == id);

			if (cartInDb == null)
			{
				return HttpNotFound();
			}

			_context.Carts.Remove(cartInDb);
			_context.SaveChanges();

			return RedirectToAction("Mine");
		}
		/*
		//Edit cart for user
		[HttpGet]
		[Authorize(Roles = "guest")]
		public  ActionResult Edit(int id)
		{
			var cartInDb = _context.Carts.SingleOrDefault(p => p.Id == id);
			if (cartInDb == null)
			{
				return HttpNotFound();
			}
			var viewmodel = new CartViewModel
			{
				Cart = cartInDb,
				Products = _context.Products.ToList()
			};
			return View(viewmodel);
		}

		[ValidateAntiForgeryToken]
		[HttpPost]
		[Authorize(Roles = "guest")]

		public ActionResult Edit (Cart cart)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}
			var cartInDb = _context.Carts.SingleOrDefault(p => p.Id == cart.Id);

			if (cartInDb == null)
			{
				return HttpNotFound();
			}
			
			cartInDb.Product.Name = cart.Product.Name;
			_context.SaveChanges();

			return RedirectToAction("Mine");
		}
		*/
	}
}

Database_1/Controllers/ProductsController.cs
using Database_1.Models;
using Database_1.Repositories.Interface;
using Database_1.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Database_1.Controllers
{
	public class ProductsController : Controller
	{
		private IProductRepository _productRepos;
		private ICategoryRepository _categoryRepos;

		public ProductsController(IProductRepository productRepos, ICategoryRepository categoryRepository)
		{
			_productRepos = productRepos;
			_categoryRepos = categoryRepository;
		}

		// GET: Products
		[HttpGet]
		public ActionResult Index(string searchString)
		{
			if (!String.IsNullOrEmpty(searchString))
			{
				return View(_productRepos.GetAllProductsWithSearchString(searchString).ToList());
			}

			return View(_productRepos.GetAllProducts().ToList());
		}

		[HttpGet]
		[Authorize(Roles = "admin")]
		public ActionResult Create()
		{
			var viewModel = new ProductCategoryViewModel
			{
				Categories = _categoryRepos.GetCategories()
			};
			return View(viewModel);
		}

		[HttpPost]
		[Authorize(Roles = "admin")]
		[ValidateAntiForgeryToken]
		public ActionResult Create(Product product)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}

			if (_productRepos.CheckExistProductName(product.Name))
			{
				ModelState.AddModelError("Name", "Product Name Already Exists.");
				return View();
			}

			_productRepos.CreateProduct(product);

			return RedirectToAction("Index");
		}

		[HttpGet]
		[Authorize(Roles = "admin")]

		public ActionResult Delete(int id)
		{
			if (!_productRepos.DeleteProductById(id))
			{
				return HttpNotFound();
			}

			return RedirectToAction("Index");
		}

		[HttpGet]
		[Authorize(Roles = "admin")]
		public ActionResult Edit(int id)
		{
			var productInDb = _productRepos.GetProductById(id);

			if (productInDb == null)
			{
				return HttpNotFound();
			}

			var viewModel = new ProductCategoryViewModel
			{
				Product = productInDb,
				Categories = _categoryRepos.GetCategories()
			};

			return View(viewModel);
		}

		[HttpPost]
		[Authorize(Roles = "admin")]
		public ActionResult Edit(Product product)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}

			if (!_productRepos.EditProduct(product))
			{
				return HttpNotFound();
			}

			return RedirectToAction("Index");
		}
	}
}

Database_1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Home", "Index", "Home")</li>
					<li>@Html.ActionLink("Product", "Index", "Products")</li>
					@if (Request.IsAuthenticated && User.IsInRole("admin"))
					{
						<li>@Html.ActionLink("Categories", "Index", "Categories")</li>
						<li>@Html.ActionLink("All Carts", "Index", "Carts")</li>
					}
					@if (Request.IsAuthenticated && User.IsInRole("guest"))
					{
						<li>@Html.ActionLink("My Cart", "Mine", "Carts")</li>
					}
					<li>@Html.ActionLink("Role", "Index", "Role")</li>
				</ul>
				@Html.Partial("_LoginPartial")
			</div>
		</div>
	</div>
	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
		</footer>
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>